# Generated by Django 4.1 on 2024-01-26 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_customuser_options_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(default=1234, max_length=5),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{15}$", "Phone number must be 15 digits Maximum"
                    )
                ],
            ),
        ),
    ]
