# Generated by Django 4.1 on 2024-01-26 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_customuser_is_verified_customuser_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,15}$", "Phone number must be 15 digits Maximum"
                    )
                ],
            ),
        ),
    ]
