# Generated by Django 4.1 on 2024-02-06 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("duration", models.CharField(max_length=100)),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Virtual"), (2, "Physical")]),
                ),
                ("veneu", models.CharField(max_length=200)),
                ("url_location", models.CharField(max_length=200)),
                ("description", models.CharField(default="", max_length=2000)),
                ("guest_descriotion", models.CharField(default="", max_length=2000)),
                (
                    "ticket_pricing_description",
                    models.CharField(default="", max_length=2000),
                ),
                ("banner", models.ImageField(null=True, upload_to="event/banner")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="events", to="notification.groups"
                    ),
                ),
            ],
        ),
    ]
