# Generated by Django 5.0.6 on 2024-07-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_pricing_description',
            field=models.CharField(default='event info', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
