# Generated by Django 4.1 on 2024-02-06 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="guest_descriotion",
            new_name="guest_description",
        ),
    ]
