# Generated by Django 4.1 on 2024-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_guest_descriotion_event_guest_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="url_location",
            field=models.CharField(max_length=2000),
        ),
    ]
