# Generated by Django 4.1 on 2024-01-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generalmembership",
            old_name="membership_type",
            new_name="general_membership_type",
        ),
        migrations.RemoveField(
            model_name="studentmembership",
            name="country_of_institution",
        ),
        migrations.RemoveField(
            model_name="studentmembership",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="studentmembership",
            name="university",
        ),
        migrations.AddField(
            model_name="membership",
            name="membership_type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "General"),
                    (2, "Institutional"),
                    (3, "Lifetime"),
                    (4, "Student"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="studentmembership",
            name="BachelorDocuments",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="management.bachelordocuments",
            ),
        ),
    ]
