# Generated by Django 4.1 on 2024-02-06 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="associated_user",
        ),
    ]
