# Generated by Django 4.1 on 2024-01-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "management",
            "0002_rename_membership_type_generalmembership_general_membership_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmembership",
            name="upgrade_request",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="generalmembership",
            name="dob",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="website",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="studentmembership",
            name="dob",
            field=models.DateField(),
        ),
    ]
