# Generated by Django 4.1 on 2024-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_studentmembership_upgrade_request_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalmembership",
            name="masters_document",
        ),
        migrations.RemoveField(
            model_name="studentmembership",
            name="college_id_card",
        ),
        migrations.AddField(
            model_name="generalmembership",
            name="educational_document",
            field=models.FileField(null=True, upload_to="educational_document"),
        ),
        migrations.AddField(
            model_name="studentmembership",
            name="educational_document",
            field=models.FileField(null=True, upload_to="educational_document"),
        ),
    ]
