# Generated by Django 4.1 on 2024-01-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0004_remove_generalmembership_masters_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalmembership",
            name="general_membership_type",
        ),
        migrations.AlterField(
            model_name="membership",
            name="membership_number",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
