# Generated by Django 4.1 on 2024-01-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "management",
            "0005_remove_generalmembership_general_membership_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalmembership",
            name="bachelor_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bachelors_members",
                to="management.bachelordocuments",
            ),
        ),
        migrations.AlterField(
            model_name="generalmembership",
            name="master_information",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bachelors_members",
                to="management.masterdocuments",
            ),
        ),
        migrations.AlterField(
            model_name="generalmembership",
            name="phd_information",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bachelors_members",
                to="management.phddocuments",
            ),
        ),
        migrations.AlterField(
            model_name="studentmembership",
            name="BachelorDocuments",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="management.bachelordocuments",
            ),
        ),
    ]
