# Generated by Django 4.1 on 2024-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_generalmembership_upgrade_membership_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalmembership",
            name="upgrade_payment",
            field=models.BooleanField(default=False),
        ),
    ]
