# Generated by Django 4.1 on 2024-01-26 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_alter_generalmembership_bachelor_information_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmembership",
            name="expected_pass_year",
        ),
    ]
