# Generated by Django 4.1 on 2024-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_generalmembership_upgrade_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalmembership",
            name="salutation",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name="StudentMembership",
        ),
    ]
