# Generated by Django 4.1 on 2024-01-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0007_remove_studentmembership_expected_pass_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalmembership",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="institutionalmembership",
            name="remarks",
        ),
        migrations.AddField(
            model_name="membership",
            name="remarks",
            field=models.TextField(null=True),
        ),
    ]
