# Generated by Django 4.1 on 2024-07-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0007_alter_generalmembership_salutation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalmembership",
            name="salutation",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
