# Generated by Django 4.1 on 2024-01-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0008_remove_generalmembership_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmembership",
            name="additional_info",
            field=models.TextField(null=True),
        ),
    ]
