# Generated by Django 4.1 on 2024-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0009_alter_generalmembership_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalmembership",
            name="salutation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
