# Generated by Django 4.1 on 2024-01-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0009_studentmembership_additional_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentmembership",
            old_name="BachelorDocuments",
            new_name="bachelor_information",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_ss",
            field=models.ImageField(null=True, upload_to="payment"),
        ),
    ]
