# Generated by Django 4.1 on 2024-01-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "management",
            "0010_rename_bachelordocuments_studentmembership_bachelor_information_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_ss",
            field=models.FileField(null=True, upload_to="payment"),
        ),
    ]
