# Generated by Django 5.0.6 on 2024-07-11 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmembership',
            name='nationaldocument',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_membership', related_query_name='associated_membership', to='management.nationaldocumment'),
        ),
    ]
