# Generated by Django 4.1 on 2024-01-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0011_alter_payment_payment_ss"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalmembership",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="studentmembership",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="generalmembership",
            name="bachelor_information",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bachelors_members",
                to="management.bachelordocuments",
            ),
        ),
    ]
