# Generated by Django 5.0.6 on 2024-08-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_generalmembership_nationaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmembership',
            name='renew_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalmembership',
            name='renew_request',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
