# Generated by Django 4.1 on 2024-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0013_educationaldocuments_nationaldocumment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalmembership",
            name="educational_document",
        ),
        migrations.RemoveField(
            model_name="studentmembership",
            name="educational_document",
        ),
        migrations.AddField(
            model_name="educationaldocuments",
            name="educational_document",
            field=models.FileField(null=True, upload_to="educational_document"),
        ),
    ]
