# Generated by Django 4.1 on 2024-02-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0015_remove_studentmembership_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionalmembership",
            name="company_document",
            field=models.FileField(null=True, upload_to="institutional_documents"),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="contact_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="contact_person",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="logo",
            field=models.ImageField(null=True, upload_to="institutional_documents"),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="pan_document",
            field=models.FileField(null=True, upload_to="institutional_documents"),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="registration_document",
            field=models.FileField(null=True, upload_to="institutional_documents"),
        ),
        migrations.AlterField(
            model_name="institutionalmembership",
            name="working_field",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
