# Generated by Django 4.1 on 2024-02-02 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0016_alter_institutionalmembership_company_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institutionalmembership",
            name="company_document",
        ),
    ]
