# Generated by Django 4.1 on 2024-02-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.BooleanField(),
        ),
    ]
