# Generated by Django 4.1 on 2024-02-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_alter_notifications_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="groups",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="notifications",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
